# Generated by Django 2.0.7 on 2018-10-05 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='readTimes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
